version: "3.5"
services:
  master:
    image: tcimba/hadoop-cluster:latest
    container_name: hadoop-master
    hostname: hadoop-master
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: home
        target: /home
      - type: volume
        source: hdfs-data
        target: /usr/local/hadoop/hdfs/data
      - type: volume
        source: logs
        target: /usr/local/hadoop/logs
      - type: volume
        source: zookeeper-data
        target: /usr/local/zookeeper/data
#      - type: bind
#        source: ${CONFIG_FOLDER}/workers
#        target: /usr/local/hadoop/etc/hadoop/workers
#      - type: bind
#        source: ${CONFIG_FOLDER}/zoo.cfg
#        target: /usr/local/zookeeper/conf/zoo.cfg
    ports:
      - "9870:9870"
      - "8088:8088"
      - "8047:8047"
      - "19888:19888"
      - "22"
    networks:
      - hadoop-net
    command: ${WORKER_NUMBER} 0
networks:
  hadoop-net:
    driver: overlay
    external:
      name: hadoop-net
volumes:
  home:
  hdfs-data:
  logs:
  zookeeper-data:
